In [1]:
pip install aiohttp==3.7.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting aiohttp==3.7.0
  Downloading aiohttp-3.7.0-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 15.6 MB/s eta 0:00:00
Collecting chardet<4.0,>=2.0
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 KB 9.8 MB/s eta 0:00:00
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp==3.7.0) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp==3.7.0) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp==3.7.0) (6.0.4)
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.8/dist-packages (from yarl<2.0,>=1.0->aiohttp==3.7.0) (2.10)
Installing collected packages: chardet, async-timeout, aiohttp
  Attempting uninstall: chardet
    Found existing installation: chardet 4.0.0
    Uninstalling chardet-4.0.0:
      Successfully uninstalled chardet-4.0.0
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 4.0.2
    Uninstalling async-timeout-4.0.2:
      Successfully uninstalled async-timeout-4.0.2
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.8.4
    Uninstalling aiohttp-3.8.4:
      Successfully uninstalled aiohttp-3.8.4
Successfully installed aiohttp-3.7.0 async-timeout-3.0.1 chardet-3.0.4

In [1]:
pip install nest_asyncio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nest_asyncio
  Downloading nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Installing collected packages: nest_asyncio
Successfully installed nest_asyncio-1.5.6

In [2]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.6.0.20230303-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 KB 3.7 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from snscrape) (3.9.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from snscrape) (2022.7.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.26.14)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.6.0.20230303

In [3]:
import nest_asyncio
nest_asyncio.apply()

In [4]:
import snscrape.modules.twitter as sntwitter
import pandas as pd


# Creating list to append tweet data to
Tweets_dfsept = []
# Using TwitterSearchScraper to scrape data and append tweets
for i,tweetsept in enumerate(sntwitter.TwitterSearchScraper('banjir jakarta since:2022-09-01 until:2022-09-30').get_items()):
    if i>10000:
        break
    Tweets_dfsept.append(tweetsept)

# Creating a dataframe from the tweets list above
Tweets_dfsept2 = pd.DataFrame(Tweets_dfsept)
Tweets_dfsept2

,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,https://twitter.com/Pakde26080592/status/15755...,2022-09-29 17:53:54+00:00,@Mdy_Asmara1701 Keren untuk saat ini tapi bula...,@Mdy_Asmara1701 Keren untuk saat ini tapi bula...,1575544413203312640,"{'username': 'Pakde26080592', 'id': 1550842958...",0,0,0,0,...,1.575478e+18,"{'username': 'Mdy_Asmara1701', 'id': 133485348...","[{'username': 'Mdy_Asmara1701', 'id': 13348534...",None,None,None,None,None,None,None
1,https://twitter.com/Batax_Nasional/status/1575...,2022-09-29 16:25:39+00:00,@BrahmaKumbara23 @wellplayed1111 @Liverpo65621...,@BrahmaKumbara23 @wellplayed1111 @Liverpo65621...,1575522203965489153,"{'username': 'Batax_Nasional', 'id': 228615995...",2,0,0,0,...,1.575472e+18,"{'username': 'BrahmaKumbara23', 'id': 15647665...","[{'username': 'BrahmaKumbara23', 'id': 1564766...",None,None,None,None,None,None,None
2,https://twitter.com/doelpaten/status/157551661...,2022-09-29 16:03:27+00:00,"@YRadianto Dusta Anies, mudah mengatasi macet ...","@YRadianto Dusta Anies, mudah mengatasi macet ...",1575516615617105920,"{'username': 'doelpaten', 'id': 11941694948321...",0,0,1,0,...,1.575410e+18,"{'username': 'YRadianto', 'id': 2542665199, 'd...","[{'username': 'YRadianto', 'id': 2542665199, '...",None,None,None,None,None,None,None
3,https://twitter.com/dianto_rusdian/status/1575...,2022-09-29 15:58:44+00:00,@TotokSSH @budimandjatmiko @jokowi Bendungan C...,@TotokSSH @budimandjatmiko @jokowi Bendungan C...,1575515427446591494,"{'username': 'dianto_rusdian', 'id': 179653268...",1,0,1,0,...,1.575279e+18,"{'username': 'TotokSSH', 'id': 134198103561393...","[{'username': 'TotokSSH', 'id': 13419810356139...",None,None,None,None,None,None,None
4,https://twitter.com/detikcom/status/1575490707...,2022-09-29 14:20:30+00:00,Pemprov DKI melakukan gerebek lumpur di lima w...,Pemprov DKI melakukan gerebek lumpur di lima w...,1575490707225452544,"{'username': 'detikcom', 'id': 69183155, 'disp...",1,2,6,0,...,NaN,None,None,None,None,None,None,"{'title': 'Antisipasi Banjir, Pemprov DKI Gere...",None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,https://twitter.com/fadlidzon/status/156518498...,2022-09-01 03:49:14+00:00,Kepedulian presiden Jokowi thd pembangunan lay...,Kepedulian presiden Jokowi thd pembangunan lay...,1565184982171074560,"{'username': 'fadlidzon', 'id': 2796357878, 'd...",0,0,0,0,...,NaN,None,None,None,None,"[BersamaJokowi, IndonesiaMaju]",None,None,None,None
1864,https://twitter.com/obrolanpublik/status/15651...,2022-09-01 02:39:43+00:00,Padahal faktanya penanganan banjir Jakarta era...,Padahal faktanya penanganan banjir Jakarta era...,1565167487834288128,"{'username': 'obrolanpublik', 'id': 1551143981...",0,1,1,0,...,NaN,None,None,None,None,None,None,None,None,None
1865,https://twitter.com/merahputihsuara/status/156...,2022-09-01 02:39:25+00:00,Padahal faktanya penanganan banjir Jakarta era...,Padahal faktanya penanganan banjir Jakarta era...,1565167413397966848,"{'username': 'merahputihsuara', 'id': 15498101...",0,1,1,0,...,NaN,None,None,None,None,None,None,None,None,None
1866,https://twitter.com/teropongsuara/status/15651...,2022-09-01 02:39:02+00:00,Padahal faktanya penanganan banjir Jakarta era...,Padahal faktanya penanganan banjir Jakarta era...,1565167318682210306,"{'username': 'teropongsuara', 'id': 1549788955...",0,1,2,0,...,NaN,None,None,None,None,None,None,None,None,None
1867,https://twitter.com/keG752/status/156516086263...,2022-09-01 02:13:23+00:00,@ariefrasyad Semua itu akan mudah diatasi kala...,@ariefrasyad Semua itu akan mudah diatasi kala...,1565160862637490176,"{'username': 'keG752', 'id': 100230795, 'displ...",0,0,1,0,...,1.564833e+18,"{'username': 'ariefrasyad', 'id': 38112151, 'd...","[{'username': 'ariefrasyad', 'id': 38112151, '...",None,None,None,None,None,None,None

In [8]:
# convert date time to date
Tweets_dfsept2['date'] = Tweets_dfsept2['date'].apply(lambda a: pd.to_datetime(a).date()) 
# save to excel
Tweets_dfsept2.to_excel('banjirJakarta2022sept.xlsx')